// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUtbn646NjcOJe5YXOVLlL6Rw3WrFooA',
    appId: '1:584672560306:web:ba1b3a96a93e16a0d3b5ab',
    messagingSenderId: '584672560306',
    projectId: 'shopee-app-28d2d',
    authDomain: 'shopee-app-28d2d.firebaseapp.com',
    storageBucket: 'shopee-app-28d2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzkN8Qc6pQ9fIanDHL6k9EgpVF_gf3TvM',
    appId: '1:584672560306:android:49afcc7f67214ba9d3b5ab',
    messagingSenderId: '584672560306',
    projectId: 'shopee-app-28d2d',
    storageBucket: 'shopee-app-28d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgHzKJwTs9JRgvAgc7PbEiUXz0cGmJY5k',
    appId: '1:584672560306:ios:0ad981fcdec1cbddd3b5ab',
    messagingSenderId: '584672560306',
    projectId: 'shopee-app-28d2d',
    storageBucket: 'shopee-app-28d2d.appspot.com',
    iosBundleId: 'com.example.shopeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgHzKJwTs9JRgvAgc7PbEiUXz0cGmJY5k',
    appId: '1:584672560306:ios:0ad981fcdec1cbddd3b5ab',
    messagingSenderId: '584672560306',
    projectId: 'shopee-app-28d2d',
    storageBucket: 'shopee-app-28d2d.appspot.com',
    iosBundleId: 'com.example.shopeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUtbn646NjcOJe5YXOVLlL6Rw3WrFooA',
    appId: '1:584672560306:web:72fcb1696027b330d3b5ab',
    messagingSenderId: '584672560306',
    projectId: 'shopee-app-28d2d',
    authDomain: 'shopee-app-28d2d.firebaseapp.com',
    storageBucket: 'shopee-app-28d2d.appspot.com',
  );
}
